#
###################################
# Site wide configuration
####################################
#
title: Luke Lefebure
email:
description: My blog and personal site
url: # the base hostname & protocol for your site


#
###################################
# Jekyll configuration
####################################
#
timezone:          US/Pacific
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Luke Lefebure
  avatar: profile_pic.jpg
  job: "Data Scientist"
  bio: "I am a data scientist, athlete, and traveler."
  email:
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-83929462-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: llefebure
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: luke-lefebure-35263056
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
